### ISSUE TITLE
no `doc/environment.yml`

### ISSUE THREAD

**Issue by Joeperdefloep** [xarray-contrib/xarray-simlab#174]
in [contributing to documentation](https://xarray-simlab.readthedocs.io/en/latest/develop.html#contributing-to-documentation) there is a reference to `doc/environment.yml` that is not there.
I added this (auto-generated) in #173

**Comment by benbovy** [comment]
Ah good catch. The environment used for building the docs has been relocated in `ci/requirements/doc.yml`, we should probably change the path in the contributing guide instead.

**Comment by benbovy** [comment]
Closed in #173.
